services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: group13
      POSTGRES_DB: group13
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
